#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the bitcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
// NOTE: Hardcoded seeds disabled for mainnet
// Junkcoin uses DNS seeds for peer discovery (see chainparams.cpp):
//   - mainnet.junk-coin.com
//   - junk-seed.s3na.xyz
//   - jkc-seed.junkiewally.xyz
// Network isolation from Litecoin is achieved via different port (9771 vs 9333)
// despite using same magic bytes (0xfbc0b6db)
static const uint8_t chainparams_seed_main[] = {
    // Empty - no hardcoded seeds
};

static const uint8_t chainparams_seed_test[] = {
    // Empty - Litecoin testnet seeds removed
    // Use DNS seeds or -addnode for testnet connections
};
#endif // BITCOIN_CHAINPARAMSSEEDS_H
